/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CarreraController;

/**
 *
 * @author Yendry León Matarrita C24251
 */
public class AdmCarreras extends javax.swing.JFrame {
    


    /**
     * Creates new form Carreras
     */
    public AdmCarreras() {
        initComponents();
        CarreraController carreraController = new CarreraController(this, panelBotones1);
        panelBotones1.listen(carreraController);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelBotones1 = new view.PanelBotones();
        panelDataCarreras1 = new view.PanelDataCarreras();
        jlFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmOpcionesCa = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();
        jmVerCa = new javax.swing.JMenu();
        miRegistroCarreras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administracion y Mantenimiento de Carreras");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));
        getContentPane().add(panelBotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));
        getContentPane().add(panelDataCarreras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        jlFondo.setText("jLabel2");
        jlFondo.setMaximumSize(new java.awt.Dimension(600, 600));
        jlFondo.setMinimumSize(new java.awt.Dimension(600, 600));
        jlFondo.setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jmOpcionesCa.setText("Opciones");

        miSalir.setText("Salir");
        jmOpcionesCa.add(miSalir);

        jMenuBar1.add(jmOpcionesCa);

        jmVerCa.setText("Ver");

        miRegistroCarreras.setText("Ver Registro de Cursos");
        jmVerCa.add(miRegistroCarreras);

        jMenuBar1.add(jmVerCa);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JMenu jmOpcionesCa;
    private javax.swing.JMenu jmVerCa;
    private javax.swing.JMenuItem miRegistroCarreras;
    private javax.swing.JMenuItem miSalir;
    private view.PanelBotones panelBotones1;
    private view.PanelDataCarreras panelDataCarreras1;
    // End of variables declaration//GEN-END:variables
}
