/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Usuario
 */
public class PanelDataPlanesEstudio extends javax.swing.JPanel {

    /**
     * Creates new form PanelDataPlanesEstudio
     */
    public PanelDataPlanesEstudio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFechaAprobacion = new javax.swing.JTextField();
        jlIdPlanEstudio = new javax.swing.JLabel();
        txtCreditosTotal = new javax.swing.JTextField();
        jlSede = new javax.swing.JLabel();
        jsDescripcionPlan = new javax.swing.JScrollPane();
        txaDescripcionPlan = new javax.swing.JTextArea();
        jlFechaAprobacion = new javax.swing.JLabel();
        jlBloque = new javax.swing.JLabel();
        txtSede = new javax.swing.JTextField();
        jlGrado = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jlTotalCreditos = new javax.swing.JLabel();
        jlDescripcionPlan = new javax.swing.JLabel();
        cbGrado = new javax.swing.JComboBox<>();
        cbCantidadBloque = new javax.swing.JComboBox<>();
        txtIdPlanEstudio = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(600, 600));

        jlIdPlanEstudio.setText("Id Plan de Estudio:");

        jlSede.setText("Sede:");

        txaDescripcionPlan.setColumns(20);
        txaDescripcionPlan.setRows(5);
        jsDescripcionPlan.setViewportView(txaDescripcionPlan);

        jlFechaAprobacion.setText("Nombre de la Carrera:");

        jlBloque.setText("Cantidad de Bloques:");

        jlGrado.setText("Grado:");

        btnBuscar.setText("Buscar");

        jlTotalCreditos.setText("Total de Creditos:");

        jlDescripcionPlan.setText("Descripción del Plan:");

        cbGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion", "Diplomado", "Bachillerato", "Licenciatura", "Maestria", "Curso Libre - Tecnico" }));

        cbCantidadBloque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTotalCreditos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCreditosTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlDescripcionPlan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsDescripcionPlan))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlBloque)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbCantidadBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                        .addComponent(jlGrado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jlIdPlanEstudio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdPlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jlSede)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSede, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(jlFechaAprobacion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFechaAprobacion)))
                                .addGap(12, 12, 12)))
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdPlanEstudio)
                    .addComponent(txtIdPlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSede)
                    .addComponent(txtSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFechaAprobacion)
                    .addComponent(txtFechaAprobacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBloque)
                    .addComponent(jlGrado)
                    .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCantidadBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTotalCreditos)
                    .addComponent(txtCreditosTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDescripcionPlan)
                    .addComponent(jsDescripcionPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbCantidadBloque;
    private javax.swing.JComboBox<String> cbGrado;
    private javax.swing.JLabel jlBloque;
    private javax.swing.JLabel jlDescripcionPlan;
    private javax.swing.JLabel jlFechaAprobacion;
    private javax.swing.JLabel jlGrado;
    private javax.swing.JLabel jlIdPlanEstudio;
    private javax.swing.JLabel jlSede;
    private javax.swing.JLabel jlTotalCreditos;
    private javax.swing.JScrollPane jsDescripcionPlan;
    private javax.swing.JTextArea txaDescripcionPlan;
    private javax.swing.JTextField txtCreditosTotal;
    private javax.swing.JTextField txtFechaAprobacion;
    private javax.swing.JTextField txtIdPlanEstudio;
    private javax.swing.JTextField txtSede;
    // End of variables declaration//GEN-END:variables
}
